GET http://localhost:3001/api/blogs

###
GET http://localhost:3001/api/blogs/685e664138f45ec846d07512

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "CSS is awesome",
  "author": "Jhin",
  "url": "http://example.com"
}

###
PUT http://localhost:3001/api/blogs/68660a9012cf03f6e2f8b3f4
Content-Type: application/json

{
  "title": "CSS is confusing",
  "author": "Ashe",
  "url": "http://example.com"
}



###
DELETE http://localhost:3001/api/blogs/685e6f9a00c18d6187df21c2
