GET http://localhost:3001/api/blogs

###
GET http://localhost:3001/api/blogs/685e664138f45ec846d07512

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpoaW4iLCJpZCI6IjY4NzczOTI1ZWNkMTk5YTIwNmI4OGI3ZiIsImlhdCI6MTc1MzQzMTAzNCwiZXhwIjoxNzUzNDM0NjM0fQ.-pCo65CdoGxGouONo0RUiE3eAE2Z1QsHtYnukYgTHww

{
  "title": "Chalex The Great",
  "author": "jhin",
  "url": "http://yahoo.com"
}

###
PUT http://localhost:3001/api/blogs/68833c30921d74523926c585/like
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpoaW4iLCJpZCI6IjY4NzczOTI1ZWNkMTk5YTIwNmI4OGI3ZiIsImlhdCI6MTc1MzQzMTAzNCwiZXhwIjoxNzUzNDM0NjM0fQ.-pCo65CdoGxGouONo0RUiE3eAE2Z1QsHtYnukYgTHww

{
  "title": "Edi wow",
  "author": "Ashe",
  "url": "http://example.com"
}



###
DELETE http://localhost:3001/api/blogs/68773931ecd199a206b88b82
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpoaW4iLCJpZCI6IjY4NzczOTI1ZWNkMTk5YTIwNmI4OGI3ZiIsImlhdCI6MTc1MjY0MzkyMywiZXhwIjoxNzUyNjQ3NTIzfQ.qFIzhWc2gGW9kAEEa9WFyFY5e0T7nwL-oQRCSb0CDXQ


###
DELETE http://localhost:3001/api/blogs/
