GET http://localhost:3001/api/users

###
GET http://localhost:3001/api/users/6870c589e69e5b40ef8dbe54

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "ashe",
  "name": "ashe",
  "password": "Ashe1234"
}

###
DELETE http://localhost:3001/api/users/68770be28f7525411d3b8d58

###
DELETE http://localhost:3001/api/users
